### ISSUE TITLE
教材アップロードできないです

### ISSUE THREAD

**Issue by shoo1-k** [novemdecillion/magic-lantern#19]
やっぱりエラー．．．ボケてるかなぁ
![image](https://user-images.githubusercontent.com/85542691/121657871-c5327900-cadb-11eb-9ea6-6dc25341e542.png)

[security2021_1_20210611_2.zip](https://github.com/novemdecillion/magic-lantern/files/6637020/security2021_1_20210611_2.zip)

**Comment by novemdecillion** [comment]
MacでZipファイルのMIMEをJavaScriptで確認するとapplication/zipだが、Windows環境ではapplication/x-zip-compressedとなっていた。
