### ISSUE TITLE
教材：タイトルは消せない？

### ISSUE THREAD

**Issue by shoo1-k** [novemdecillion/magic-lantern#20]
これ、消せないのかなぁ？
![image](https://user-images.githubusercontent.com/85542691/121710152-4148b300-cb14-11eb-9149-cd82e413309c.png)
![image](https://user-images.githubusercontent.com/85542691/121710342-7b19b980-cb14-11eb-995b-b97899970748.png)

**Comment by novemdecillion** [comment]
基本的にはexplain-template.htmlではなくHTMLを用意してもらうことになります。

また今回、no-title-explain-template.htmlを用意しましたので、explain-template.htmlの代わりに指定していただけばタイトルは表示されません。

**Comment by shoo1-k** [comment]
ありがとーございます。
