### ISSUE TITLE
教材が出てこない．．．

### ISSUE THREAD

**Issue by shoo1-k** [novemdecillion/magic-lantern#22]
教材あるのに．．．
![image](https://user-images.githubusercontent.com/85542691/121773140-dbf8ce80-cbb4-11eb-945e-a274a3911055.png)
出てこないよ．．．
![image](https://user-images.githubusercontent.com/85542691/121773169-05b1f580-cbb5-11eb-833e-36c30976b105.png)

**Comment by novemdecillion** [comment]
問題はsecurityの教材が表示されないことではなく、講座が1件も表示されないことでした。
これはあるグループに受講者が1名も存在しないことで発生する例外によるものです。

securityの教材は、講座権限を持つ全てのグループで使用されており、講座追加画面で表示されないのは正常です。
