### ISSUE TITLE
アンケート答えないで戻るとエラー

### ISSUE THREAD

**Issue by shoo1-k** [novemdecillion/magic-lantern#27]
進捗率0%からアンケートページを開き、アンケート答えないで戻ると．．．
![image](https://user-images.githubusercontent.com/85542691/121794662-37729d00-cc45-11eb-9c31-af19f207fa3c.png)
エラー
![image](https://user-images.githubusercontent.com/85542691/121794678-51ac7b00-cc45-11eb-8669-ca7b01a630c6.png)

**Comment by novemdecillion** [comment]
逆戻りして試験に遷移した場合は、1ページ目を表示するようにした。
2ページ目の進捗は未のままなので、合格にはならなくなる。
