### ISSUE TITLE
グループインポートできないです。教えて。

### ISSUE THREAD

**Issue by shoo1-k** [novemdecillion/magic-lantern#30]
すみません。一回目インポートしたら、何も表示されなかったので、もう一回やったらこんな表示に。
ファイルが悪いんだと思うのですが、何が悪いのか．．．
![image](https://user-images.githubusercontent.com/85542691/121843867-03b77600-cd1e-11eb-99c9-18804b8b5c3c.png)

**Comment by novemdecillion** [comment]
インポート自体は成功しているのですが、部門名に  / が存在するのを想定できておらず、グループ一覧の表示に失敗しています。
部門名に 「 / 」が存在しても大丈夫なように対応します。
