### ISSUE TITLE
教材権限を付けるにはどーすれば良い？

### ISSUE THREAD

**Issue by shoo1-k** [novemdecillion/magic-lantern#36]
グループの権限設定に教材が無い．．．

ユーザにあったので権限付けたけど．．．

**Comment by novemdecillion** [comment]
ユーザ編集で変更できます。

ユーザ数が多くて画面に反映されるのに時間がかかる場合があります。

**Comment by shoo1-k** [comment]
変わらないですね．．．ユーザ編集で教材権限付けても

どーすれば教材権限がつけられます？

**Comment by novemdecillion** [comment]
正常に教材権限は付与されています。
