### ISSUE TITLE
教材が見えなくなりました。

### ISSUE THREAD

**Issue by shoo1-k** [novemdecillion/magic-lantern#37]
教材をアップロードしたけど、表示されず．．．
![image](https://user-images.githubusercontent.com/85542691/122516538-db938400-d049-11eb-82f4-51a0275aa127.png)
でも、存在はしてるように見える。
![image](https://user-images.githubusercontent.com/85542691/122516741-1990a800-d04a-11eb-900c-15ed90758e75.png)

**Comment by novemdecillion** [comment]
config.ymlの 73行目と 88行目の設定がおかしいです。

![image](https://user-images.githubusercontent.com/76469770/122517672-4a251180-d04b-11eb-8d42-4b1d98cf4799.png)
