### ISSUE TITLE
受講でエラー

### ISSUE THREAD

**Issue by shoo1-k** [novemdecillion/magic-lantern#40]
教材が悪いと思うのですが、どこが悪いのか分からず．．．
教材はサーバでconfig.ymlを編集しました。
/var/lib/docker/volumes/magic-lantern_slides_data/_data/2021senmonkensetu/config.yml

**Comment by novemdecillion** [comment]
教材を直接viを編集するのは、誤字を修正する等の緊急対応用です。

学習中に、問題を追加するのは動作保証外でお願いします。
