### ISSUE TITLE
並び替えされてしまう

### ISSUE THREAD

**Issue by shoo1-k** [novemdecillion/magic-lantern#47]
![image](https://user-images.githubusercontent.com/85542691/142347108-401a3b9e-2790-415a-adfa-963730e73beb.png)
![image](https://user-images.githubusercontent.com/85542691/142347172-1bc962e5-43eb-42d9-b662-10c2b273fcfd.png)

**Comment by novemdecillion** [comment]
これは #44 の10問中3門が表示されるランダムではなく、問題の並べ替えの話ですね。
並べ替えの機能は、現状解除できません。

**Comment by novemdecillion** [comment]
並び替えを抑制するフラグを教材に追加。

```
option:
    shuffleQuestions: false
    shuffleChoices: false
```

* ランダム出題と併用して、出題順を固定にすると、必ず同じ問題が出題されるようになる。
* 途中でこの設定を変えた場合、既に開始した受講は元のまま。
