### ISSUE TITLE
合格したはずが不合格

### ISSUE THREAD

**Issue by shoo1-k** [novemdecillion/magic-lantern#49]
すみません。e-ラーニング受講者のかたから、問い合わせがありました。
－－－－－
下記実施しているのですが、
１回目で合格（満点）したあと、アンケート回答し、
さらに黄色の右矢印をクリックしいると、
なぜか、不合格になってしまいます。

その後は、何度回答しても、
回答結果がクリアされ不合格になってしまいます。
－－－－－
なんか、わかりますでしょうか？

**Comment by novemdecillion** [comment]
セッションの扱いに問題があり、DBに状態を保存するように 1dba595c254c3f6cf6189607a19d0b5903342b13 で修正。
